misc:
  run_mode: test # Mode to run the network in
  num_points: 99999 # Number of points
  use_gpu: True # If GPU should be used or not
  visualize: False
  savefig: False
  index_list: [54] # 16, 21, 34, 37, 57, 141 

data:
  dataset: StereoKITTI_ME # Name of the dataset [StereoKITTI_ME FlyingThings3D_ME SemanticKITTI_ME LidarKITTI_ME WaymoOpen_ME]
  root: ../../dataset/sceneflow_eval_dataset/KITTI_o/withNormal/ # --- withNormal --- 
  remove_ground: True # Remove ground by simple thresholding of the height coordinate
  augment_data: True # Augment the data by random rotation and translation
  only_near_points: True # Only consider near points (less than 35m away) [Used in all scene flow algorithms]
  only_front_points: False
  filter_normals: False

test:
  batch_size: 1 # Test batch size
  num_workers: 8 # Num of workers to use for the test data set
  
hyperparameters:
  box_depth: 4
  box_scale: 1.25
  sigmoid_slope: 8
  epsilon: .01
  background_boost_coeff: 0
  heading_loss_coeff: 1000
  angle_loss_coeff: .01
  mass_loss_coeff: .001
  dim_loss_coeff: 8
  prune_threshold: 80
  confidence_threshold: .85
  seg_threshold: .01
  print_loss: False
  lr: .0152
  epochs: 1750
  delta_threshold: 0
  cycle: False
  cycle_threshold: 0
  evaluate_train: False